Repository nbc-ijo/nbc-ijo, pull requests merged in 2024-02, with the labels that each got.

#1 template 적용
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: documentation

#16 Feature/issue 15
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/spring/nbcijo/controller/MyPageController.java
  src/main/java/com/spring/nbcijo/dto/request/UpdateDescriptionRequestDto.java
  src/main/java/com/spring/nbcijo/entity/Comment.java
  src/main/java/com/spring/nbcijo/entity/User.java
  src/main/java/com/spring/nbcijo/global/enumeration/ErrorCode.java
  src/main/java/com/spring/nbcijo/repository/CommentRepository.java
  src/main/java/com/spring/nbcijo/service/MyPageService.java
  src/test/java/com/spring/nbcijo/comment/CommentControllerTest.java
  src/test/java/com/spring/nbcijo/comment/CommentRepositoryTest.java
  src/test/java/com/spring/nbcijo/comment/CommentRequestDtoTest.java
  src/test/java/com/spring/nbcijo/comment/CommentServiceTest.java
  src/test/java/com/spring/nbcijo/common/CommentFixture.java
  src/test/java/com/spring/nbcijo/common/ControllerTest.java
  src/test/java/com/spring/nbcijo/common/PostFixture.java
  src/test/java/com/spring/nbcijo/jwt/JwtUtilTest.java
  src/test/java/com/spring/nbcijo/mypage/MyPageControllerTest.java
  src/test/java/com/spring/nbcijo/mypage/MyPageServiceTest.java
  src/test/resources/application-test.properties
Labels: documentation, enhancement, feat

#18 Feature/issue 5
  src/main/java/com/spring/nbcijo/controller/PostController.java
  src/main/java/com/spring/nbcijo/dto/request/PostRequestDto.java
  src/main/java/com/spring/nbcijo/dto/response/PostResponseDto.java
  src/main/java/com/spring/nbcijo/entity/Post.java
  src/main/java/com/spring/nbcijo/service/PostService.java
  src/test/java/com/spring/nbcijo/post/PostRequestDtoTest.java
Labels: feat

#24 feat: 게시글 조회 기능
  src/main/java/com/spring/nbcijo/controller/PostController.java
  src/main/java/com/spring/nbcijo/service/PostService.java
Labels: feat

#26 feat: 게시글 전제 조회 기능
  src/main/java/com/spring/nbcijo/controller/PostController.java
  src/main/java/com/spring/nbcijo/service/PostService.java
Labels: feat

#33 Feature/issue 27
  src/main/java/com/spring/nbcijo/controller/PostController.java
  src/main/java/com/spring/nbcijo/entity/Post.java
  src/main/java/com/spring/nbcijo/service/PostService.java
Labels: feat

#34 Feature/issue 29
  src/main/java/com/spring/nbcijo/controller/PostController.java
  src/main/java/com/spring/nbcijo/service/PostService.java
Labels: feat

#30 Feature/issue-28
  src/main/java/com/spring/nbcijo/controller/MyPageController.java
  src/main/java/com/spring/nbcijo/repository/CommentRepository.java
  src/main/java/com/spring/nbcijo/service/MyPageService.java
Labels: feat

#32 Feature/issue-22 refreshToken 기능 추가
  src/main/java/com/spring/nbcijo/config/WebSecurityConfig.java
  src/main/java/com/spring/nbcijo/jwt/JwtUtil.java
  src/main/java/com/spring/nbcijo/security/JwtAuthenticationFilter.java
  src/main/java/com/spring/nbcijo/security/JwtAuthorizationFilter.java
Labels: documentation, enhancement, feat

#35 Feature/issue 31
  src/main/java/com/spring/nbcijo/controller/MyPageController.java
  src/main/java/com/spring/nbcijo/repository/PostRepository.java
  src/main/java/com/spring/nbcijo/service/MyPageService.java
Labels: feat

#36 Feature/issue 17
  src/main/java/com/spring/nbcijo/controller/CommentController.java
  src/main/java/com/spring/nbcijo/controller/MyPageController.java
  src/main/java/com/spring/nbcijo/dto/request/UpdatePasswordRequestDto.java
  src/main/java/com/spring/nbcijo/entity/PasswordHistory.java
  src/main/java/com/spring/nbcijo/entity/User.java
  src/main/java/com/spring/nbcijo/global/enumeration/ErrorCode.java
  src/main/java/com/spring/nbcijo/repository/PasswordHistoryRepository.java
  src/main/java/com/spring/nbcijo/service/CommentService.java
  src/main/java/com/spring/nbcijo/service/MyPageService.java
  src/main/java/com/spring/nbcijo/service/UserService.java
  src/test/java/com/spring/nbcijo/comment/CommentControllerTest.java
Labels: bug, enhancement, feat

#46 Feature/issue 39
  src/main/java/com/spring/nbcijo/dto/response/PostResponseDto.java
  src/main/java/com/spring/nbcijo/entity/Post.java
  src/main/java/com/spring/nbcijo/entity/User.java
  src/test/java/com/spring/nbcijo/common/PostFixture.java
  src/test/java/com/spring/nbcijo/post/PostControllerTest.java
  src/test/java/com/spring/nbcijo/post/PostServiceTest.java
  src/test/java/com/spring/nbcijo/post/PostTestUtils.java
Labels: test
